### ISSUE TITLE
After playing, let lights return to previous state

### ISSUE THREAD

**Issue by Fietspomp86** [ericmatte/ad-media-lights-sync#15]
Is it possible to let the lights go back to their original state before they are changed by this addon?
When I stop playback, the lights stay at the state which was set by the addon.

Also, I've tested it with Kodi, works ok.

**Comment by thundergreen** [comment]
I made this with an automation. but would be nice having this ntively :)

**Comment by ericmatte** [comment]
As @thundergreen said, one can simply make an automation for that. For my setup, I use a simple automation that turns off the light when I stop playback.

I try to keep this app rather simple, but I am also open to PRs :)
