### ISSUE TITLE
Define transition time for color changes

### ISSUE THREAD

**Issue by katekyonni** [ericmatte/ad-media-lights-sync#18]
**Is your feature request related to a problem? Please describe.**

Some lights (im my case LIFX) change colors instantly without a transition.

**Describe the solution you'd like**

Define a default transition time for the color change.

I think its really distracting if the colors change instantly, would be great if this could be implemented!

**Comment by ericmatte** [comment]
Hi,

Does your LIFX lights support the `transition` property in Home Assistant? https://www.home-assistant.io/integrations/light/

If yes, then it would be possible to also add a `transition` property to 
`ad-media-lights-sync` (which would defaults to null).

**Comment by katekyonni** [comment]
Yes the transition property is supported.
If you could add the option that would be amazing, thank you! 👍

**Comment by ericmatte** [comment]
Great; I should be taking a look into implementing this soon.

**Comment by ericmatte** [comment]
@katekyonni the code has been added in the last release ([v0.5.0](https://github.com/ericmatte/ad-media-lights-sync/releases/tag/v0.5.0)).

Cheers!

**Comment by katekyonni** [comment]
Thank you :)
