### ISSUE TITLE
RGB lights support - ESP8266

### ISSUE THREAD

**Issue by marima84** [ericmatte/ad-media-lights-sync#2]
Hi @ericmatte,
In this issue report #1 I forgot to mention that my led stripe is on a ESP8266 with ESPhome firmware. In case you want to add it in your compatibility list.
Thanks

Mark

**Comment by ericmatte** [comment]
Great, thank you for taking the time to let me know. Updated in [**v0.2.1**](https://github.com/ericmatte/ad-media-lights-sync/releases/tag/v0.2.1).
