### ISSUE TITLE
Add a feature to assign parts of the thumbnail to a specific lights

### ISSUE THREAD

**Issue by mnayef95** [ericmatte/ad-media-lights-sync#20]
It's will be clever if I can assign each part of the image to a specific light.

This image will explain what I want

![New Project](https://user-images.githubusercontent.com/25001862/98809006-a4128880-2425-11eb-9bad-2bbc607b4836.png)

And I can choose which part. for which light

**Comment by ericmatte** [comment]
That would be great indeed.

Currently I am using the Pillow python package in order to give me a color palette equals in length to the amount of linked lights: https://github.com/ericmatte/ad-media-lights-sync/blob/master/apps/media_lights_sync/media_lights_sync.py#L61

From what I know, their is no way to know from what part of the image the color came from; as the palette is just a list of the most prominent colors in the image.

Also, how would you change the [configuration](https://github.com/ericmatte/ad-media-lights-sync#app-configuration) in order to make that setup?

**Comment by ericmatte** [comment]
I think the easiest way to achieve a setup like that in real-time would be with a set of RGB Philips Hue combined the [Play HDMI Sync Box](https://www.philips-hue.com/en-ca/p/hue-play-hdmi-sync-box-/046677555221); or with their [PC sync app](https://www.philips-hue.com/en-ca/entertainment/sync-with-pc).

**Comment by mnayef95** [comment]
@ericmatte Actually I'm thinking of it as a Lovelace card that showing all lights, same as this:

![Screen Shot 2020-11-11 at 8 09 51 PM](https://user-images.githubusercontent.com/25001862/98848134-ece43480-2459-11eb-9dc9-336bba8b3129.png)

And we will change the light icon to another icon, once the user clicks on it we will show a dialog with one static image, and the user can draw one square on that image and we will take the square position as a Rect object and save them on some file with the image width and height, and then we will slice the media player image to multiple parts (except if Pillow giving us the position of the color on the image), based on the user drawing on the previous step, then we will extract the colors from the images and reflect them to the light that assigned to the part.

**Comment by ericmatte** [comment]
This goes beyond a python [AppDaemon](https://appdaemon.readthedocs.io/en/latest/) app and would actually need an frontend integration as well plus some way to communicate between the app and the frontend entity 🤔

**Comment by mnayef95** [comment]
@ericmatte You are right, maybe we can create a frontend integration for assigning the lights to the parts of the image and the integration will create a JSON file that contains all data about the lights and Rects so the AppDaemon app will read these data and reflect it to the light.

I don't know if we can separate this to another AppDaemon app as well

**Comment by ericmatte** [comment]
Yeah that would makes sense.

And how would you communicate that JSON file with the AppDaemon app?

Also, I am using `Image.open(f).quantize(colors=len(self.lights)).getpalette()` from Pillow which only returns me a list of colors from the thumbnail's palette without any information about their location. I'm not sure how we could get that missing information.

**Comment by mnayef95** [comment]
I think we can split the image into multiple images based on the JSON file, and extract the colors from each image and reflect it to the assigned color

**Comment by ericmatte** [comment]
That could be an idea.
And then we could probably do something like `Image.open(f).quantize(colors=1).getpalette()` for each sub image.

But I also like how Hue Sync do it:

<img src="https://user-images.githubusercontent.com/9013072/99151929-8c791100-266c-11eb-9bf4-e1cddc3f9eff.png" width="200" />

You just have to visually place your RGB lights in order for them to get the color that matches their physical location.

**Comment by mnayef95** [comment]
I didn't use it before, I'm planning to get one this month, Is there any way to integrate the sync app with non-hue lights?

**Comment by ericmatte** [comment]
`ad-media-lights-sync` works with any RGB lights available in Home Assistant.
The Hue Sync app from Philips will only works with Philips Hue lights.

**Comment by ericmatte** [comment]
I will close this issue; as I probably won't be implementing something like this in this app in the near future.

This goes outside of the scope selected for this simple app, but thank you for the idea.
