### ISSUE TITLE
Is there a way to sync the lights with music frequency?

### ISSUE THREAD

**Issue by mnayef95** [ericmatte/ad-media-lights-sync#22]
I'm curious if we can get the music frequency from the media player and reflect them to the lights, is there any way to get this information from the Home Assistant?

**Comment by ericmatte** [comment]
From what I see in my `media_player` attributes, this doesn't seem to be available.

![2020-11-11 at 18 52](https://user-images.githubusercontent.com/9013072/98877705-177cc000-244f-11eb-8935-1f2825573369.png)

**Comment by mnayef95** [comment]
@ericmatte based on the documentation from **[spotify](https://developer.spotify.com/documentation/web-api/reference/tracks/)**, it's can be done, so maybe if the media player is Spotify we can get the media info and reflect them to the brightness, so while the music is playing using Spotify the light brightnesses will be changed based on the frequency and the colors will be extracted from the thumbnail

**Comment by ericmatte** [comment]
This is a cool idea.
And indeed, it seems to be available in the Spotify API.

However, this would greatly increase the complexity of this simple AppDaemon app; as it would need to run a server in parallel only for the Spotify API plus managing additional client id/secret and authentication process.

From what I see, this should made in a secondary AppDaemon app:
- The `ad-media-lights-sync` extracts the colors from the thumbnail using HA
- The second app could connect to Spotify, process the audio analysis from the Spotify API and update in real-time the brightness from the lights based on the frequency.

To make `ad-media-lights-sync` not interfere with the brightness controlled by that secondary app, you can use this setting:
```yaml
use_current_brightness: true
```

While this is a great idea, I think that it goes outside of the scope of this application.
Making that code on a separated app would be a better separation of concerns. I will close this issue.

**Comment by mnayef95** [comment]
That makes since
