### ISSUE TITLE
Add All Amazon media player compatibility ( Fire TV, echo dot, echo show, ....)

### ISSUE THREAD

**Issue by MaAamie** [ericmatte/ad-media-lights-sync#23]
Add compatibility with Amazon media player.

**Comment by ericmatte** [comment]
Hi,

is this a feature request or you want to inform that the app works with all Amazon media players?

If they are available in Home Assistant as `media_player`; they should work with this app without any problem.

**Comment by MaAamie** [comment]
sorry. exactly i meant it works for amazon echo dot.

**Comment by ericmatte** [comment]
Great! Thank you for the information!

**Comment by ericmatte** [comment]
I've updated the README compatibility section (https://github.com/ericmatte/ad-media-lights-sync/commit/16b43662383c973cc81a3f62a69737874a82bcd6). Thank you.
