### ISSUE TITLE
Help install - AppDaemon Configuration

### ISSUE THREAD

**Issue by nandox1** [ericmatte/ad-media-lights-sync#26]
after added to APPDEAMON 4 config the included info
system_packages:
  - py3-pillow
python_packages:
  - Pillow

server gives me  Failed to save addon configuration, not a valid value for dictionary value @ data['options']. Got {'system_packages': ['py3-pillow'], 'python_packages': ['Pillow']}

any help?

**Comment by nandox1** [comment]
looking at clodes issue previosly resolved, i resolved my problem.

**Comment by ericmatte** [comment]
@nandox1 I've updated the README [Prerequisites section](https://github.com/ericmatte/ad-media-lights-sync/blob/master/README.md#prerequisites) to be more clear about that :)
