### ISSUE TITLE
Unclear documentation - how to install?

### ISSUE THREAD

**Issue by jbrepogmailcom** [ericmatte/ad-media-lights-sync#29]
### Describe the bug

Hello, your installation instructions say "download to apps directory". I am running HASSIO, I do not see any apps directory even if I launch terminal add-on a do ls or ls ..

Where is the apps directory and how to download it there if running HASSIO?

(the HACS approach does not work for me either).

Thanks, Jan

**Comment by ericmatte** [comment]
Hi @jbrepogmailcom,

What exactly is not working with HACS?
You should be able to install it under:
- `HACS` -> `Automation` -> <kbd>EXPLORE & ADD REPOSITORIES</kbd> -> and search for `Media Player Lights Sync`.

---

Also, if you want to install it manually, the AppDaemon app directory in HassIO should be located under `config/appdaemon/apps`.
You should be able to access it using add-ons like `Samba share` or `File editor`.

**Comment by jbrepogmailcom** [comment]
Hello,

I have file in
config/appdaemon/apps/media_lights_sync/media_lights_sync.py

I also have added modules to appdaemon configuration. Then I added configuration to configuration.yaml. When I check the configuration I get config error "**Component error: media_lights_sync - Integration 'media_lights_sync' not found.**"

I am afraid I am missing something which is not written in installation instructions.

**Comment by ericmatte** [comment]
@jbrepogmailcom AppDaemon has nothing to do with you Home Assistant `configuration.yaml` file.
The error you're getting is saying that you are trying to add an invalid integration to Home Assistant; which is the case.

---

### To fix your issue:

1. Remove what you've added in the `configuration.yaml` file
2. Following the [Prerequisites](https://github.com/ericmatte/ad-media-lights-sync#prerequisites) section of the readme, add this to your AppDaemon configuration in the Supervisor:
  ![image](https://user-images.githubusercontent.com/9013072/107063501-7630ac00-67a8-11eb-81cc-741808dfe119.png)
3. Put this [App Configuration](https://github.com/ericmatte/ad-media-lights-sync#app-configuration) in your `config/appdaemon/apps/apps.yaml` file (this is the file to use for AppDaemon apps.)
4. Restart HA and AppDaemon
5. Everything should be working if properly configured


---

Please check this thread for more information:
https://community.home-assistant.io/t/please-help-trying-to-set-up-appdaemon-and-i-havent-got-a-clue/163187
And I would suggest you to also read the [AppDaemon documentation](https://appdaemon.readthedocs.io/en/latest/APPGUIDE.html#).

I will close this issue and update the README to point out the path to the App Configuration file.
