### ISSUE TITLE
Better algorithm to identify prevalent color (duplicated)

### ISSUE THREAD

**Issue by jbrepogmailcom** [ericmatte/ad-media-lights-sync#32]
**Is your feature request related to a problem? Please describe.**

Dear sir,

if I am not mistaken, your script identifies best color by averaging colors in whole album. That results in mostly gray colors with some tint of prevalent color. I would like to ask you to consider different approach.

I use my own color analysis for years and I am very satisfied with it. I downsize the album, posterize it to less colors and then run statistical analysis to find what color is mostly represented in the album. This way if album is 55% red and 45% green, the result is not brown but red. Mail me at jbrepo@gmail.com and I will send you the script - I understand I cannot attach files here. It also has some approximation to 10 colors that are most similar. You can just replace fetching image by hass instead from last.fm and you can skip color approximation and call to ifttt at the end and you will have excellent album color finder.

Jan

**Comment by ericmatte** [comment]
Hi @jbrepogmailcom,

Thanks for the idea, but I don't think that this is necessary, as the current algorithm used already extract a list of the most present colors in the artwork matching the number of RGB lights you've linked with the app.

See the examples from the README:

<img src="https://github.com/ericmatte/ad-media-lights-sync/raw/master/examples/example-2.jpg" alt="Example 1" width="400">

In this example, the two colors extracted from the album image are red and a purple-blue; which is mostly the two main colors of the current image.

If you think that the colors are more on the gray side, you can try with the option `use_saturated_colors: true`; which will increase the saturation.

---

Also for sharing code snippet, you can use https://gist.github.com/, create a public repo, or fork this one.

**Comment by ericmatte** [comment]
This issue and issue #34 are mostly the same; I will close this one as duplicated.
