### ISSUE TITLE
Colors don't change from standby mode to album mode when restarting the same song

### ISSUE THREAD

**Issue by jbrepogmailcom** [ericmatte/ad-media-lights-sync#33]
### Describe the bug

Hello Eric, I made following observation. It may not be a bug, but rather a behaviour. When I start playing song (or a movie on KODI), the RGB bulb turns to correct color. When I stop the song, it turns back to normal color as it was before. But when I start to play the same song again, the bulb **does not** switch to album color. I assume that it is before image of current album is still cached and the script does not detect album change. This could possibly be solved by clearing album image on media player stop - the Home Assistant may do it, or just wipes the image album from lovelace card when it detects media player stop event and does not show it, but image may still be cached somewhere.

I personally have also problem with librespot, because it detects only when spotify switches from mobile phone to that player, it does not detect song change. But I think it is a problem of librespot, because HA lovelace card does not show song change either.

Best regards, Jan

**Comment by ericmatte** [comment]
Good catch; there was a variable that wasn't cleared when the lights are reset.
It is fixed here 5b3e71f5c9fba04b481fd6adc2cd70e0fa2f68a2 and will be available in the next release.

**Comment by jbrepogmailcom** [comment]
Can you please explain me how to update the script? Do I need to do it manually, or is there some mechanism in Home Assistant for automatic updates?

**Comment by ericmatte** [comment]
@jbrepogmailcom using [HACS](https://hacs.xyz/) is the easiest way to update AppDaemon apps like this one. Once I will make a new release, a notification will appear in the HACS on your Home Assistant to update it.

Otherwise, you can manually update your code using the code `media_lights_sync.py` on the master branch.

**Comment by ericmatte** [comment]
I've just released version [v0.7.0](https://github.com/ericmatte/ad-media-lights-sync/releases/tag/v0.7.0) with the related fix. 🎉
