### ISSUE TITLE
Unavailable on hacs

### ISSUE THREAD

**Issue by hacshacdgacs** [ericmatte/ad-media-lights-sync#41]
With the new monthly HA updates this is no longer available through hacs.

**Comment by ericmatte** [comment]
Hi, sorry for the delay in response.

If I check the list of default available apps from HACS, this repo should be still available:

https://hacs.xyz/default_repositories/
![image](https://user-images.githubusercontent.com/9013072/123974710-d4923d00-d98a-11eb-8f31-acf97394a50b.png)


Could you give me more info on the problem?

**Comment by ericmatte** [comment]
I just tried to uninstall/reinstall it, and it was still available to download through HACS.

Note that you must be in the `Automation` section of HACS to see it.

I will close this issue. Feel free to re-open the issue or reply if anything.

![CleanShot 2021-06-30 at 10 13 02](https://user-images.githubusercontent.com/9013072/123976001-cbee3680-d98b-11eb-8f8c-99578002e1ef.png)

![image](https://user-images.githubusercontent.com/9013072/123976339-0d7ee180-d98c-11eb-9a6e-fc08631bcc70.png)

**Comment by ericmatte** [comment]
If you don't see then `Automation` tab (AppDaemon), make sure to enable it:

https://hacs.xyz/docs/categories/appdaemon_apps/#enable-appdaemon-apps-in-hacs
