### ISSUE TITLE
working with Logitech Squeezebox integration

### ISSUE THREAD

**Issue by Engelbert** [ericmatte/ad-media-lights-sync#45]
**Is your feature request related to a problem? Please describe.**
No.

**Description of what the problem is.**
There is no problem.

**Describe the solution you'd like**
None.

**Describe alternatives you've considered**
None.

**Additional context**
As titel mentions, it's working with the Logitech Squeezebox integration. You can add it to the list.
Thanks for the app!

**Comment by ericmatte** [comment]
Thank you for the info! It's added to the README. 👍 1a45758abaedad5fb1306be4e0d03eb97833f0fd
