### ISSUE TITLE
No longer functioning - Unable to fetch artwork

### ISSUE THREAD

**Issue by lichenophile** [ericmatte/ad-media-lights-sync#47]
### Describe the bug
No longer produces a resulting colour change of my LIFX light-bulbs.
Previously working. 
My config hasn't changed, and I've checked all configuration is still correct. 
No errors is output log. 

### Steps to reproduce the behaviour:
1. Toggle the associated input boolean to on
2. Play the next track in spotify
3. No resulting colour change on my LIFX bulbs

### Expected behaviour:
Colour change of my LIFX bulbs based on album art

### Environment versions:
- ad-media-lights-sync: Latest version v1.0.0
- Home Assistant: core-2021.11.5, supervisor-2021.12.1
- AppDaemon: AppDaemon 4 v0.7.1

### Additional context

HA media player still functions and displays album art, Spotify Mood Lights Sync also still behaves as expected.

![image](https://user-images.githubusercontent.com/67679349/145617369-17a3a560-16b0-4c64-ae83-c100f2f078a7.png)

**Comment by lichenophile** [comment]
![image](https://user-images.githubusercontent.com/67679349/146307183-f5ec8a10-29be-49de-8df1-83e709e2b9c9.png)
Thought to add the Appdaemon log output of the error, the rest of the log for media_lights_sync looks fine.

I also notice this url loads an image just fine in web browser, regardless of being logged in to HA or not.

**Comment by ericmatte** [comment]
Hi @grastraa,

I just validated and everything is working correctly on my side.

Maybe a config did changed with your router?
Try changing your `ha_url` for something else, like the IP address. Or try removing it from the `media_lights_sync:` config.

I'm noticing you are using `http` instead of `https` in your url. Are you sure that your HA instance is not using https?

---

If that does not work, try editing `` to bypass SSL certificate:

![image](https://user-images.githubusercontent.com/9013072/147136178-b8944eb8-55a9-4ebd-83d9-2ab062a9ab6d.png)

```py
import ssl
# ...
fd = urlopen(url, context=ssl._create_unverified_context())
```

I tried that with my own instance, and it can fix this error for some setups.

**Comment by lichenophile** [comment]
Thanks very much for the help. I am indeed _not_ using SSL. 
Out of the above suggestions, what I found to work is to use the local IP address as http://homeassistant.local:8123/ does not function. 
I'm now unsure of my original functioning configuration and why it stopped working in the first place, but glad to have it going again, many thanks.

The other thing that I can't seem to make correctly function is including `!secret ha_url`, despite my secrets.yaml containing the same local IP address, formatted exactly the same. I even tried it out with your modified code above with no luck. Odd, but perhaps this a change I made at some point and forgot about, which lead to my initial issue?

Either way, it'll do for now. Thanks again!

**Comment by ericmatte** [comment]
From what I saw, it seems that secrets used in the `apps.yaml` are loaded only when AppDaemon starts. So if you need to update a secret in your `secrets.yaml`, you also need to restart AppDaemon.

Glad you've found a solution for your problem. I will close the issue.

Cheers
