### ISSUE TITLE
Yandex.Station

### ISSUE THREAD

**Issue by dengi76** [ericmatte/ad-media-lights-sync#56]
Hello! Is it possible to add support for Yandex Station? Thank you.

**Comment by ericmatte** [comment]
Hi @dengi76!

The [compatibility list](https://github.com/ericmatte/ad-media-lights-sync#compatibility) on the README shows what devices have been tested and works with this app, but the app should work with any `media_player` and RGB light integrations available in Home Assitant.

I don't have a Yandex Station, but if can output a thumbnail on its `media_player` in Home Assistant, it should work.

**Comment by dengi76** [comment]
Understood thanks!
