### ISSUE TITLE
Option to ignore completely black entity pictures

### ISSUE THREAD

**Issue by katekyonni** [ericmatte/ad-media-lights-sync#58]
Hi,

would it be possible to ignore new entity pictures that are just black instead of changing all lights to 'rgb_color': [0, 0, 0] ?

I'm syncing the colors of an Android TV device and sometimes Home Assistant gets a black entity_picture.
Unfortunately, some of my Zigbee lights turn to a bright green when set to 'rgb_color': [0, 0, 0]  and I would like to avoid that.

Maybe there could be an option to ignore changes to 'rgb_color': [0, 0, 0] and 'rgb_color': [255, 255, 255], so completely black and white pictures get skipped?

Thank you for considering this!

**Comment by ericmatte** [comment]
Hi, this is a good idea.

`0,0,0` is not a very pertinent color for RGB lights. I could simply skip the update if the color is pure black.

`255,255,255` however could be useful for some pictures.

I could check to add a skip all black when I will have some free time.

**Comment by katekyonni** [comment]
That would really help in my case, thank you :)

**Comment by ericmatte** [comment]
All right! I will make something :)

**Comment by ericmatte** [comment]
@katekyonni I've just released [v1.2.0](https://github.com/ericmatte/ad-media-lights-sync/releases/tag/v1.2.0) which includes this feature!
