### ISSUE TITLE
Optional expose and publish all bulb colour values as attributes (also regardless of sync being enabled)

### ISSUE THREAD

**Issue by lichenophile** [ericmatte/ad-media-lights-sync#59]
I have _no idea_ how to python but have added a optional sensor that populates its state and attribute to an rgb value generated (I'm not sure which)
![image](https://user-images.githubusercontent.com/67679349/210198825-c1ca6508-2442-40f6-bdeb-2a76711ed5e2.png)
https://github.com/ericmatte/ad-media-lights-sync/compare/master...lichenophile:ad-media-lights-sync:master
Forgive my poor implementation, it's literally some cut an paste of a snippet I found elsewhere!

I'm having trouble figuring out how to:
1) have these attributes pushed even if I do not wish to have lights syncing to these colours
2) a way to have all colours generated for bulbs to be published as separate attributes correctly (less important)

I realise this might be a niche sorta request and out of scope for a project that is about syncing lights specifically, so no stress.

As an example of use, this allows me to template my media player card icon and progress bar colours to complement the blurred album art background.
(I'm using modified code from[ this persons fantastic customised mushroom card](https://community.home-assistant.io/t/mushroom-cards-build-a-beautiful-dashboard-easily/388590/4304?u=d0doooh) for anyone interested)
![image](https://user-images.githubusercontent.com/67679349/210198813-ed175f7e-e965-4773-b9a7-25fe98397bb3.png)

Another idea is to have the ability to try to always give a attribute for a colour steal that contrasts the overall colour of the image, so it doesn't blend with the background at all, or just different enough that it doesn't blend to the point of losing visability.

**Comment by ericmatte** [comment]
Interresting. Maybe I could set multiple attributes on the same sensor, one attribute per light.

Do you need this as a "reference/mirror" of the colors being currently used by the RGB lights, or you want the ability to use it regardless if you have some light setup or not?

**Comment by lichenophile** [comment]
The latter I suppose, as I can already check and template the former using my light sensors rgb_color attributes. 
However, I am using this with lights set up, there are just times I wish to see what the lights would be set to, without those values being pushed to the lights (ie. when the input_boolean is off).

Also having colour values regardless of having any light(s) set up would be useful for theming cards of my many media player entities that don't have associated lights. 
I currently only really _need_ one colour output to use for this, but being able to output a palette of X extra colours and/or saturated colours along side the regular ones would be extra useful (to me at least haha)

In the case of a configuration of light sync with X amount of bulbs, using each lights entity name as the title of the tried colour attribute would make sense.

For a configuration of two lights, (regardless of light sync being enabled) a sensor to output attributes something like:
```
kitchen_north: 191, 63, 63
kitchen_south: 63, 191, 191
extra_1: 191, 63, 127
kitchen_north_saturated: 191, 0, 0
kitchen_south_saturated: 0, 191, 191
extra_1_saturated: 191, 0, 96
```

I realise publishing all these extra values unrelated to actual values pushed to lights is quickly spiralling out of scope of this project. Maybe I need to learn some python myself!

**Comment by ericmatte** [comment]
Yeah, this is out of scope for this project, so I think that we will close this issue.

However, here is what you could do: you could modify the script of this app a little to fit your needs.

Something like that for 1 colour only:

```diff
    def change_lights_color(self, entity, attribute, old_url, new_url, kwargs):
        """Callback when a entity_picture has changed."""
        if new_url == old_url or not self.can_change_colors():
            return

        if new_url is not None:
            self.store_initial_lights_states()
            log_message = "New picture received from '{entity}' ({attribute})\n"
            current_pictures = [self.get_state(entity, attribute=attribute) for attribute in PICTURE_ATTRIBUTES]

            if self.media_player_callbacks.get(entity, None) == current_pictures:
                # Image already processed from another callback
                return self.log(log_message.format(entity=entity, attribute=attribute + "; skipped"))
            self.log(log_message.format(entity=entity, attribute=attribute))

            try:
                url = self.format_url(new_url, entity, attribute)
                rgb_colors = self.get_colors(url)
            except (HTTPError, URLError) as error:
                self.error("Unable to fetch artwork: {error}\nURL: {url}\n".format(url=url, error=error))
                return

            self.media_player_callbacks[entity] = current_pictures
+            self.set_state(self.sensor, replace=True, state=self.get_saturated_color(rgb_colors[i]), attributes = {"color": self.get_saturated_color(rgb_colors[0])})
-            for i in range(len(self.lights)):
-                color = self.get_saturated_color(rgb_colors[i]) if self.use_saturated_colors else rgb_colors[i]
-                self.set_light("on", self.lights[i], color=color, brightness=self.brightness, transition=self.transition)
        else:
            self.reset_lights()

    def get_colors(self, url):
        """Get the palette of colors from url."""
        context = ssl.SSLContext() if not self.verify_cert else None
        fd = urlopen(url, context=context)
        f = io.BytesIO(fd.read())
        im = Image.open(f)
        if im.mode == "RGBA" and self.quantization_method not in [None, Image.FASTOCTREE, Image.LIBIMAGEQUANT]:
            im = self.convert_rgba_to_rgb(im)

-        palette = im.quantize(colors=len(self.lights), method=self.quantization_method).getpalette()
-        return self.extract_colors(palette, len(self.lights))
+        palette = im.quantize(colors=1, method=self.quantization_method).getpalette()
+        return self.extract_colors(palette, 1)
```

Or this for multiple colours:

```py
# in def change_lights_color after the try/except:

self.media_player_callbacks[entity] = current_pictures
attributes = {}

for i in range(len(self.lights)):
    color = self.get_saturated_color(rgb_colors[i]) if self.use_saturated_colors else rgb_colors[i]
    attributes[self.lights[i]] = color
    self.set_light("on", self.lights[i], color=color, brightness=self.brightness, transition=self.transition)

self.set_state(self.sensor, replace=True, state="on", attributes = attributes})
```

Cheers
