### ISSUE TITLE
Continuously change color when watching a movie or series

### ISSUE THREAD

**Issue by e-ru** [ericmatte/ad-media-lights-sync#62]
**Is your feature request related to a problem? Please describe.**

Description of what the problem is.

There is no problem

**Describe the solution you'd like**

Description of what you want to happen.
 
I would like to have the light change every x seconds when watching a movie or series.
Could this be achieved by reading the image of the media player periodically via a loop and update the light accordingly?

**Describe alternatives you've considered**

Description of any alternative solutions or features you've considered.

Update the condition of the app in a  way that you can define the period of the colour change in an additional condition.

**Additional context**

It's kind of an ambilight...

**Comment by e-ru** [comment]
ok, i did the loop, but the entity_picture doesn't change. is there a way to get the data of the current picture?

**Comment by ericmatte** [comment]
Hi, sorry for the late response, but this is _somewhat_ possible if you are using an android tv, with remote debugging enabled.

Something like that: https://community.home-assistant.io/t/getting-the-image-art-from-media-player-androidtv-as-a-generic-camera/189595/7.

The only problem is that the image seems to be updating at 2-3 seconds intervals, and this script can take up to 1 seconds to process the image.
Sadly, this is too much delay to be worth it, and it is outside of the scope of this project.

I would suggest to try something like the **HDMI Hue Sync Box** by Philips Hue or the **Govee TV Backlight**, which are a better option for real-time colors sync.
