### ISSUE TITLE
Cycle trough the lights

### ISSUE THREAD

**Issue by Voluerunt** [ericmatte/ad-media-lights-sync#64]
_Description of what you want to happen._

Is it possible to make it so the colours cycle trough the lights.

For example: 

I have 5 lights, they change colour according to spotify. there are 5 different colours.
Cycle the 5 colours trough the 5 lights, so you have a party kind of effect

**Comment by ericmatte** [comment]
That could be possible, but not in my plans for now.

A pull request is always welcome.

**Comment by ericmatte** [comment]
I will close this issue due to inactivity.
