### ISSUE TITLE
EspHome not working when an effect is set

### ISSUE THREAD

**Issue by KrX3D** [ericmatte/ad-media-lights-sync#66]
Hi,

i have normally an Effect set on my esphome lights.  The color is set but i need to set it manually to SOLID so it will work.

**Comment by ericmatte** [comment]
Hi, EspHome lights are usually custom builds and are not supported directly by this project.

However, the fix should be fairly simple in your case. What I would suggest you is to go into your folder where you've `ad-media-lights-sync`, and add this line in the file `ad-media-lights-sync/apps/media_lights_sync
/media_lights_sync.py:110`:

```diff
            attributes[color_attr] = color
+           attributes["effect"] = "SOLID"
```

That should do the trick.

Feel free to re-open this issue if needed.
