### ISSUE TITLE
Errors when cover image is all black

### ISSUE THREAD

**Issue by deviantintegral** [ericmatte/ad-media-lights-sync#67]
### Describe the bug

While the first light is properly skipped, at least when using the method 400 errors are still thrown.

### To Reproduce

1. Make sure to have at least two lights configured.
2. Listen to any track from https://en.wikipedia.org/wiki/This_Is_Spinal_Tap_(soundtrack). I suggest Christmas with the Devil 🤘 🎅 . 
3. See the 400 errors like so:

> 2023-12-13 19:38:21.233807 INFO media_lights_sync: Skipped black color for 'light.pedestal_1' light
> 2023-12-13 19:38:21.235094 INFO media_lights_sync: Set 'light.pedestal_2' light:
> {'transition': 30, 'rgb_color': [], 'brightness': 255}
> 2023-12-13 19:38:21.239805 INFO media_lights_sync: Set 'light.pedestal_3' light:
> {'transition': 30, 'rgb_color': [], 'brightness': 255}
> 2023-12-13 19:38:21.245798 INFO media_lights_sync: Set 'light.pedestal_4' light:
> {'transition': 30, 'rgb_color': [], 'brightness': 255}
> 2023-12-13 19:38:21.257059 WARNING HASS: Error calling Home Assistant service default/homeassistant/turn_on
> 2023-12-13 19:38:21.295120 WARNING HASS: Code: 400, error: 400: Bad Request
> 2023-12-13 19:38:21.296774 WARNING HASS: Error calling Home Assistant service default/homeassistant/turn_on
> 2023-12-13 19:38:21.297256 WARNING HASS: Code: 400, error: 400: Bad Request
> 2023-12-13 19:38:21.297883 WARNING HASS: Error calling Home Assistant service default/homeassistant/turn_on
> 2023-12-13 19:38:21.298322 WARNING HASS: Code: 400, error: 400: Bad Request

I fixed this by changing the black check to:

```
                if color == [0, 0, 0] or len(color) == 0:
```

However, I'm not sure if this is actually best fixed elsewhere, as I'm using `  quantization_method: libimagequant` and perhaps other methods always return values.

**Comment by ericmatte** [comment]
Hi, I was not able to reproduce with the specified song and `quantization_method: libimagequant`.

However, your fix seems like an easy enough and safe patch, so I will add it just to be more safe.

Btw, nice song :)
